wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.19.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1655313112
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      2:
      - 1
      - 5
      - 11
      - 49
      4: 3.8.10
      5: 0.12.11
      6: 4.19.4
      8:
      - 5
